server:
  port: 8762
spring:
  application:
    name: service-support
eureka:
  instance:
    hostname: localhost
    appname: service-support
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



