server:
  port: 8764
spring:
  application:
    name: service-ribbon
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

